### ISSUE TITLE
Move filtration issues to this repo

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-processing#1]
Picking up an issue from web-monitoring-ui (https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/24):

> `filtration` currently has filter-related issues but no code. We should move those issues to this repo & deprecate `filtration`.

With the new tripartite web-monitoring project structure we should move the issues from filtration (https://github.com/edgi-govdata-archiving/filtration/issues) to this repo instead

**Comment by dcwalk** [comment]
I've emailed GH support and asked if they can move the issues here

**Comment by dcwalk** [comment]
Heard back and there is now way for them to move it and preserve author comments. Either have to use the [API](https://gist.github.com/jonmagic/5282384165e0f86ef105) or the tool @kmcculloch used.

I can tackle tomorrow unless someone beats me to it

**Comment by kmcculloch** [comment]
https://github-issue-mover.appspot.com/

**Comment by dcwalk** [comment]
Hey @aleatha, @aschn, @vidkum1, @hellowendy, @nadesai, @abelsouza, @ambergman, moved your issues to this repo from Filtration. Hope you all can continue your work here! (Old repo deleted as well).
