### ISSUE TITLE
New differ: list the URLs of the links before and after

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#102]
See https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/113

We want something like

```python
def diff_links(a_html, b_html):
    ...
    # return something like [(url1, url2, url3), (url4, utl5)]
```

**Comment by Mr0grog** [comment]
Note each item here should be a URL + link text pair, so if a web page had code like:

```html
<nav>
    <a href="https://epa.gov/climate">Climate Info</a>
</nav>
```

The diff should include information about both the text (`Climate Info`) and the URL (`https://epa.gov/climate`)
