### ISSUE TITLE
Fix lxml upstream

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#104]
As @janakrajchadha and @Mr0grog have discussed previously, the `htmldiff` function in the `lxml` package has a critical problem, illustrated here:

```python
In [1]: from lxml.html.diff import htmldiff

In [2]: htmldiff('<p>before</p>', '<p>after</p>')  # good
Out[2]: '<p><ins>afer</ins></p> <p><del>before</del></p>'

In [3]: htmldiff('<ins>before</ins>', '<ins>after</ins>')  # what happens to the <ins>?!
Out[3]: '<ins>after</ins> <del>before</del>'
```

It merely drops any `ins` and `del` tags in the inputs so that it can use `ins` and `del` to represent diffs without ambiguity. There are ways to avoid this ambiguity without lossily ignoring `ins` and `del` tags in the inputs. For example, it could use `ins` and `del` tags with a special CSS class or even a custom tag like `diffins` and `diffdel`. It should probably make this choice customizable through an optional parameter.

One possibility is to submit a patch to lxml upstream. Because `htmldiff` is implemented in Cython, making this change isn't trivial. To satisfy our short-term goals, it is probably better to look at other projects, but I'm opening this issue as a marker.

**Comment by janakrajchadha** [comment]
I think there's another possibility. Since lxml's `htmldiff` uses `difflib` for diffing, it's possible to mirror what lxml does in its `htmldiff`. @anastasia's code is already work in that direction and after discussing things with her, I think we can try taking this route. [Discussion here](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/78#issuecomment-328281646)
I might be missing some information here so I'm not absolutely sure about this path.

**Comment by danielballan** [comment]
Yep, I agree that `lxml` parsing + some custom code involving `difflib` is likely to be the most efficient way forward. Fixing `lxml` upstream _might_ give us better performance wins, but I'm not sure yet whether we need them.

**Comment by janakrajchadha** [comment]
If fixing `lxml` upstream is potentially going to take a lot of time and effort, we can keep that as a long term fix and work on a quick fix for now.

**Comment by Mr0grog** [comment]
I feel like, at this point, we’ve gone pretty far from lxml’s implementation (and are still moving away from it). Does contributing back upstream still make sense?

**Comment by danielballan** [comment]
Hmm. Probably not.

**Comment by Mr0grog** [comment]
Closing this, then.
