### ISSUE TITLE
Review CDX API with reference to this document

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#112]
https://github.com/internetarchive/wayback/blob/master/wayback-cdx-server/README.md

**Comment by Mr0grog** [comment]
FYI, that doc is not 100% accurate (it’s *mostly* good); some stuff just doesn’t work and other stuff is out of date. Maybe worth seeing questions I asked on #wayback-labs-g when I was working on #82.

**Comment by Mr0grog** [comment]
I think this was effectively done in 96b781778a2973641ce51515c4cbd3ff486ac9e7, so I’ll go ahead and close this.
