### ISSUE TITLE
Incorporate deployment.md into published docs.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#118]
I'd like to wait on this until v0.1 because I expect the deployment instructions will significantly change and be simplified (by being encoded in ansible for docker-compose).

**Comment by Mr0grog** [comment]
@danielballan should we close this as better handled by the [Ops repo](https://github.com/edgi-govdata-archiving/web-monitoring-ops) or do we still need to do it here?

**Comment by Mr0grog** [comment]
Or do we need to follow through on #206 first?

**Comment by Mr0grog** [comment]
I think this is pretty effectively handled by the ops repo now, so I’m going to go ahead and close it.
