### ISSUE TITLE
Create health check for Internet Archive data

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#125]
The tool that auto-submits our URLs for crawls over at Internet Archive seems to crap out every so often. As we move towards regularly importing their data, we should have something that does a regular health check to get early alerts if it looks like something’s gone wrong on their end.

This probably looks like:

1. Grab a random sampling of 5 or 10 URLs we are following
2. Look for the latest snapshots of those URLs in IA
3. If none have snapshots within the last N hours (48? 72? probably should be adjustable), fire off an alert (e-mail, Slack, pagerduty, Sentry error? Any/all are viable).

**Comment by weatherpattern** [comment]
Moved this to milestone v0.0.2 Stop Verisonista Imports.
This is still critical to have, but needed when we turn off Verisonista and move over to the Internet Archive.

**Comment by weatherpattern** [comment]
This looks to me like script that can run independently from the rest of Scanner.
I'm going to pick this up, I have a friend who might be able to help me as well, if I get stuck. Where can I find the list of domain that we are following?

**Comment by Mr0grog** [comment]
> Where can I find the list of domain that we are following?

You should query the API for this.

**Comment by weatherpattern** [comment]
@Mr0grog @danielballan which folder should the script for this live? scripts? or web_monitoring?

**Comment by weatherpattern** [comment]
For now, placed in the script in the edgi-scripts repo. It may move again later.

https://github.com/edgi-govdata-archiving/edgi-scripts/pull/28

**Comment by Mr0grog** [comment]
Closing since #172 got merged.
