### ISSUE TITLE
Data ingestion [ETL step 0]

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-processing#13]
_From @nadesai on February 11, 2017 23:51_

For each subdomain, need to ingest:
- source diff (raw HTML changes)
- bytes added
- bytes removed
- enclosing HTML tag
- context (HTML page source before/after). (Open question here - how much context is sufficient? Would a page "summary" do, or just the enclosing paragraph, instead of the full page source?)
- time diff is recorded (may not be relevant due to noise in when pages are scraped)
- Analyst feedback/annotations

_Copied from original issue: edgi-govdata-archiving/filtration#5_

**Comment by Mr0grog** [comment]
I think most of this is more or less done, while any remaining bits are already better represented in other issues. I’m closing this.
