### ISSUE TITLE
Refactor on top of html5-parser

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#138]
It seems like we should be using https://html5-parser.readthedocs.io/en/latest/ for its robustness and speed.

Once the HTML differ is working well enough and tested, we should consider refactoring on top of this.

## Differs That Need Updating

- [x] side_by_side_text
- [x] links
- [x] links_json
- [x] html_text_dmp
- [x] html_token

**Comment by Mr0grog** [comment]
Question: that parser will build a variety of trees; are you thinking we should switch to an lxml tree or stick with BeautifulSoup? If the latter, I think this: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/05a0b2550ac5a2982487087c29055600cdf8c214/web_monitoring/differs.py#L30-L35

Can just have line 32 replaced with:

```py
soup = html5_parser.parse(html, treebuilder='soup')
```

And everything else stays the same. It also happens to potentially* solve #288.

(*It solves the parsing breakage on my local machine, but not 100% sure that’s the same issue as the server is encountering.)

**Comment by Mr0grog** [comment]
Anyway, we could start with that one and expand to the other differs as we have time to double-check and make sure all the various APIs are compatible.

**Comment by vbanos** [comment]
Fix: https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/410
