### ISSUE TITLE
Improve performance of other rendered differs (or precompute and cache)

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#139]
Improve the performance of htmldiffer and htmltreediff -- or pre-compute and cache the results. Currently they take about 10 seconds, which is too long to make analyst wait.

Once this is resolved, open an issue in web-monitoring-ui to expose them there.

**Comment by Mr0grog** [comment]
As a side note here, DB now does caching of diffs (see edgi-govdata-archiving/web-monitoring-db#194 & edgi-govdata-archiving/web-monitoring-db#195). We should still see what we can do on the actual performance of these algorithms, though.

**Comment by Mr0grog** [comment]
@danielballan Should we move this off the v0.0.2 milestone? I think we decided we’re not really worried about these other differs in the short term, right?

**Comment by danielballan** [comment]
Agreed.
