### ISSUE TITLE
html diffs: Should return early with a clear error if HTML does not parse

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#147]
We should really easily be able to give better feedback than `type error` if a version does not parse as HTML (e.g. if someone fed the algorithm a PDF).

For example: https://api.monitoring.envirodatagov.org/api/v0/pages/4ca4bc6f-6dc2-4b01-8e7a-94d50baf276e/changes/e053c830-029a-4925-88c2-114b370c4fcc..8c5583c7-02f2-4ee2-a495-748865dc1330/diff/html_token?include=all

**Comment by danielballan** [comment]
@Mr0grog I understand the issue, but as a side question: is there a reason that that link is now a 404?

**Comment by Mr0grog** [comment]
Uhhhhhhh, it never *would* have worked. Dunno how I wound up with that URL (it was missing the `/api/v0` at the start of the path). Edited and updated the original post.
