### ISSUE TITLE
`html_token` differ returns different `change_count`s for same version

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-processing#148]
I noticed this while testing https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/176. I was diffing versions against themselves expecting to get 0 changes, which would trigger the messages.

When using either rendered dif, the responses are inconsistent if the versions are the same.

1) https://monitoring.envirodatagov.org/page/c307f86b-659d-4248-9db2-54188ffc19f5/9e6009fc-e222-4d4a-8182-693855205386..9e6009fc-e222-4d4a-8182-693855205386
For this page, if we select the same version, we get the expected `change_count: 0` for all of them.

2) https://monitoring.envirodatagov.org/page/24849b3d-9813-4c4e-95c6-5fc2d0cce8ce/28bd8db7-1391-4ba3-be0f-eaaf6004dd65..28bd8db7-1391-4ba3-be0f-eaaf6004dd65
For this page, if we select the same version we get `change_count: 4` instead with 2 insertions and 2 deletions.

3) https://monitoring.envirodatagov.org/page/2378b371-229c-41f7-9dcb-8a11c6d1e2ac/44374b2e-adb5-4d51-ab26-33d017ead8b1..44374b2e-adb5-4d51-ab26-33d017ead8b1
For this page, `Jan 13` diffed with itself version has 0 changes. But `Dec 28` diffed with itself has 2 changes.

**Comment by Mr0grog** [comment]
99.9% certain this is a dupe of #146 (maybe should make that one clear that it’s not really about SVG, it’s about any embedded non-HTML content, like `<math>` `<style>`, `<script>`, etc).

**Comment by lightandluck** [comment]
Ah, ok, I didn't realize that it affected the change_count too!
