### ISSUE TITLE
Discerning order of additions and removals of links next to each other is hard.

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-processing#151]
In outgoing links, when two links next to each other are additions and removals, it is hard to discern the order of the text and links.

From @Mr0grog 
OLD:
Energy Analysis (/eere/services/energy-analysis) Energy Basics (/eere/energybasics/energy-basics-old) Energy.gov Offices (/offices)

NEW:
Energy Analysis (/eere/about-us/policy-and-analysis-team) Energy.gov Offices (/offices)

There’s no great way for it to really discern that the addition of `(/eere/about-us/policy-and-analysis-team)` comes _between_ the removal of `(/eere/services/energy-analysis)` and the removal of `Energy Basics (/eere/energybasics/energy-basics-old)`. They both got removed and they come one after the other here.

Possible solution:
One thing that we _could_ do that wouldn’t be too complicated would be to show the entire line as changed. (See attached image.)
It is more verbose for all the changed links but I think reads more clearly, and is less confusing for analysts.

<img width="1075" alt="screen shot 2018-01-18 at 10 47 33 pm" src="https://user-images.githubusercontent.com/1836118/35157813-247f2458-fd03-11e7-9444-4b33466feba3.png">

**Comment by Mr0grog** [comment]
The example that started this (though there are plenty of others for sure): https://monitoring.envirodatagov.org/page/645a11e1-af58-4e8b-a1f0-75d870679603/2e8df842-5881-4393-aa6a-5a9814291305..5ee8836e-ac99-422b-b740-ff4e40f06d87
