### ISSUE TITLE
Diffing a version with no content results in an error

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#157]
This diff: https://monitoring.envirodatagov.org/page/ffd842a3-d7b7-46f1-ac16-54c04c934487/a381e497-de9c-4506-9a7c-e7f510359727..2dfc2803-1625-48a8-b069-fb2a8e4dace7

Results in an internal server error, which I’m guessing appears to be because the `a` version (`a381e497-de9c-4506-9a7c-e7f510359727`) has no content (it is actually 0 bytes). That *should* be fine, so we should see what’s choking here.

**Comment by kouell** [comment]
A few more instances of this issue:

https://monitoring.envirodatagov.org/page/76f6d82f-099a-48e1-93eb-569c8a0f52e9/62755593-55c8-49a6-a964-b7c7266645f3..e8532f5e-d202-4fb2-95c9-00f38949c473

https://monitoring.envirodatagov.org/page/48b01139-854e-4f2f-8773-6fc199c7d079/abddaf0d-9ef3-41ae-98c9-094c972d12cb..b5032217-1f26-4208-881d-256b398bcf7a

https://monitoring.envirodatagov.org/page/3482211b-cfa5-4d47-b07e-3c656e1ddb33/a162cffa-a8a6-48a5-ad38-829a8bd08be3..49f59dd1-b299-4ce2-947b-1b14d0725a16

**Comment by danielballan** [comment]
Thanks, @kouell!
