### ISSUE TITLE
Choose better colors for highlighting changes

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#158]
Splitting this thread of conversation out from #153.

Our current colors for changes can be tough to distinguish for some kinds of color vision deficiency; in particular, deuteranopia, where it looks roughly like (normal on left, simulated deuteranopia on right):

![color-deficiency](https://user-images.githubusercontent.com/74178/35879642-9712be86-0b30-11e8-95a9-708b144cb3bf.png)

@ericnost pointed out some great example combinations at http://www.visualisingdata.com/2015/11/colour-swatch-alternatives-to-green-and-red/ . @weatherpattern and I both like the first one:

![safe-colors](https://user-images.githubusercontent.com/74178/35880415-b88e4a10-0b32-11e8-9e64-18c77a80ae7a.png)

Or, in context:

![safe-colors-2](https://user-images.githubusercontent.com/74178/35880904-0470baac-0b34-11e8-8212-bd1c7424169f.png)

Not sure this is ideal yet, and would love more input here.

(Side note: deuteranopia is obviously not the only kind of color deficiency; our current colors are less terrible with others, but the suggested colors above work well across the spectrum of deficiencies. There is a good Chrome extension called [Spectrum](https://chrome.google.com/webstore/detail/spectrum/ofclemegkcmilinpcimpjkfhjfgmhieb) for testing in your browser.)

**Comment by Mr0grog** [comment]
From @ericnost: I have some color deficiencies, making it hard for me to identify the color value of the less saturated BGs. I can distinguish a difference in the two links in the bottom block of the example above, but I can't name the color. I also can't specify what color the light BGs are in the first two blocks of the example. I am not sure how often I will run into this use case scenario in my monitoring.

I do better with the solid red/green BGs, especially when there are substantial chunks of text highlighted. (And I don't think these are pure red/green to begin with?) When there are small text changes right next to each other, I sometimes can't immediately tell whether it's a removal or addition.

I don't feel burdened in my own monitoring work (which is why I haven't raised the issue before), but it might be worth testing an alternative, color-blind friendly color scheme for a broader audience. I am not sure what that would be, but there are some ideas here: http://www.visualisingdata.com/2015/11/colour-swatch-alternatives-to-green-and-red/ (maybe the first pair?)

**Comment by Mr0grog** [comment]
From @weatherpattern: @ericnost you raise a great and important point. Thanks for bringing it up and sharing the link, which is great. (How could one that opens with the colorbrewer not be?)

I like the first choice. # 4dac26 and # d01c8b
That way we don't have to reteach what green means, and the magenta color is not that far removed from the red that we're used to seeing.

**Comment by lightandluck** [comment]
+1 Also, like the first one.

**Comment by Mr0grog** [comment]
Now trying the middle pair from the swatches in the first post here via env vars in production.

**Comment by Mr0grog** [comment]
Oh wow, I totally lost track of this. We’ve been using custom colors in production for so long now! Everybody’s been happy with them, so we should bake them in: https://github.com/edgi-govdata-archiving/web-monitoring-ops/blob/f8b5a7ac049950e518b6b13f334a7d002645c79a/templates/production/diffing-deployment.yaml#L37-L40
