### ISSUE TITLE
Add issue template to processing repo

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-processing#163]
Add a template for create new issues, as mentioned in edgi-govdata-archiving/web-monitoring#97

Based on this template:
https://github.com/NSLS-II/bluesky/issues/new

**Comment by lightandluck** [comment]
This was done in #164 and merged in [9558fcd](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/164/commits/9558fcd43b534ad22fc9f25b4d575d8c1901914b) by @weatherpattern
