### ISSUE TITLE
Upgrade CircleCI to v2

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#165]
Despite the painful inanity that is configuring CircleCI v2, they are executing v1 at the end of August. So we do have to upgrade.

https://circleci.com/blog/sunsetting-1-0/

**Comment by danielballan** [comment]
Worst email I received yesterday. :- |

**Comment by Mr0grog** [comment]
Should probably set up auto-publishing to Docker Hub from the master branch when we do this, too: edgi-govdata-archiving/web-monitoring-db#246
