### ISSUE TITLE
upload web-monitoring-processing into PyPI

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-processing#168]
Install a release of web-monitoring-processing on PyPI.
That way it becomes pip installable and can be access from other repos, like edgi-scripts

**Comment by lightandluck** [comment]
@danielballan Would this still be a useful `idea`?

**Comment by Mr0grog** [comment]
I think this is better to just let someone do when they are interested in ready. At present this repo is so messy, I don’t think it does much good (i.e. we should solve #206 first) and I’m not sure tracking this as an issue is very helpful.

**Comment by lightandluck** [comment]
Makes sense 👍

This was the only `-processing` issue I had a question about
