### ISSUE TITLE
IA import scripts need option to include all snapshots

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#176]
When we import pages from the Internet Archive, we skip snapshots that were identical to the one that preceded them (since our rule with versions is that we *generally* try to make each version a version where something changed from the preceding version). We do that by [checking the hash of the content in the CDX API](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/internetarchive.py#L222-L228).

However, when IA tracks a URL, they track the exact HTTP response to that URL. We track the ultimate response that resolved from that URL (this happens to also be how Versionista does it). That’s often the same thing, but if there was an HTTP redirect (as opposed to a client-side one), that means IA is hashing different content than we are storing. This is an issue if a page gets permanently redirected to somewhere else — all IA snapshots from that point forward will have the same hash, even if the page that was redirected to is changed.

Obviously there are some good open questions about what we should really be storing, but those are a separate issue, I think. And FWIW, we do store a list of all the redirects involved in resolving a version from the Internet Archive.

We already have functionality to do this (the `skip_repeats` parameter for `internetarchive.list_versions()`), but we don’t expose it in the CLI.

- The easy first step would be to expose that option to the CLI
- We might also want to add *new* functionality to do the same kind of thing, but only *after we resolve the ultimate response* (that’s in [`internetarchive.timestamped_uri_to_version()`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/internetarchive.py#L312))

Some ideas for the CLI interface:

- `--skip-repeated <SKIPPABLE>` where values are `none`, `response` (current behavior), or `resolved-response` (or maybe `resolved` or `content`?)
- `--skip-unchanged <SKIPPABLE>` where values are `none`, `response` (current behavior), or `resolved-response` (or maybe `resolved` or `content`?)
- `--include-all`, `--skip-repeats` (current behavior), `--skip-resolved-repeats` flags that are exclusive
- `--include-all`, `--skip-immediate-repeats` (current behavior), `--skip-repeats` flags that are exclusive (make the biggest mouthful the one you probably don't want)
- `--include-all`, `--skip-unchanged-response`, `--skip-unchanged`

Is `repeated` or `unchanged` clearer terminology here? I think I’m a bit too deep in the weeds to answer that. (cc @weatherpattern @lightandluck @danielballan)

**I also think we should change the default behavior.** It seems to me that our current behavior is probably the one we don’t want. It should either be filtering the resolved results or just including everything. I don’t think this is too big a deal since nobody is really using these scripts besides us for now (so far as I know, at least).

This pertains to both the existing `wm import ia` script and the in-progress work on `wm import ia-known-pages` script (#174).

**Comment by lightandluck** [comment]
It sounds like we should change the default behavior to filter resolved results, skipping any repeats. And we would only need one flag `--include-all` when we wanted everything (_omgawd miniature archive.org for real_ 😱).

The current behavior sounds like it has a real issue there missing redirects. What would be reasons to keep it?

**Comment by Mr0grog** [comment]
> The current behavior seems like it has a very problematic issue missing what happens after redirects. What would be reasons to keep it?

It’s more correct in a strict, technical sense. In a less abstract and more applicable to our software sense, if we ever wanted to switch to a model where we stored the actual server responses instead of the resolved responses the current behavior is absolutely the option we’d want to be using. There are really good arguments for changing our model to behave that way (@danielballan and I have talked about this at least a couple times). It makes it possible to utilize our database to analyze page redirects and renames, link graphs and other things that are not very easy (perhaps not possible at all) with our database the way it is today using Versionista data (which is always the resolved result).

So I would say it’s worth keeping around for A) people wanting to use this not just for our particular install of the DB and B) for our future usage.

**Comment by lightandluck** [comment]
I like using `--skip-unchanged` with `none`, `response`, and `resolved-response`. These terms all make the most sense to me after everything being explained in the last dev meeting. It also matches with the proposed `?skip_unchanged_versions` querystring argument in -db.

Also, agree we should change default behavior to filter resolved responses because it gets around the redirect issue and less work for -db to do filtering when records are imported.

**Comment by danielballan** [comment]
I agree with @lightandluck with regard to both desired defaults and names.
