### ISSUE TITLE
IA import scripts need rate limiting and retry/backoff semantics

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#177]
As I’ve started to import a bunch of historical data from the Internet Archive, I’ve found that occasionally we hit gateway timeout errors (504 errors) when getting content. I’m not sure if we’re requesting too fast or if they just have these errors intermittently (but often enough that I am seeing them regularly).

To cover both cases, we should probably add rate limiting options as well as retry capability when resolving a URL.

**Comment by weatherpattern** [comment]
Is this worth asking about in the IA slack channel?

**Comment by Mr0grog** [comment]
No.

**Comment by Mr0grog** [comment]
This is just general good behavior.

**Comment by Mr0grog** [comment]
But I will post and ask about reasonable rates they expect to support.

**Comment by Mr0grog** [comment]
(We already do this with Versionista, for example.)
