### ISSUE TITLE
capture analyst feedback

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-processing#18]
_From @aleatha on February 12, 2017 0:4_

Analyst feedback on diffs should be stored, and used to calculate the weight of significant keywords 

_Copied from original issue: edgi-govdata-archiving/filtration#9_

**Comment by Mr0grog** [comment]
The core capacity for this is already built into `web-monitoring-db` at this point. There is a closely related task to load existing analyst work from spreadsheets in: edgi-govdata-archiving/web-monitoring-db#61

Not sure if we should keep this around or close it in favor of that task.

**Comment by danielballan** [comment]
> Not sure if we should keep this around or close it in favor of that task.

Let's close this. All of the functionality lives in web-monitoring-db.
