### ISSUE TITLE
Would we want a xml differ?

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-processing#183]
Low priority question. Posting to track.

Marcy, one of the analysts, came across a [page](https://monitoring.envirodatagov.org/page/5262f77e-1422-4f54-9109-c52dc183ab88/3c5cc089-10a0-4ee4-8859-11b71f878668..ebac6845-704c-47b1-8690-f1000684d73e) which was an xml file for the site's rss feed. We currently don't have a differ to handle xml. In this case, a changing rss feed isn't significant, but xml can be used to structure other types of data. Would we want an xml differ?

**Comment by weatherpattern** [comment]
Yes, we've come across this before, so thanks for documenting. I'd say in the short term no, but mid/long term yes. A follow up question would prioritizing it to diffing other file formats like PDF:
https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/162
https://github.com/edgi-govdata-archiving/web-monitoring/issues/36

The decision would be lead by input from the analyst team.

**Comment by Mr0grog** [comment]
I think we should keep this issue around for someone to work on.

**Comment by Mr0grog** [comment]
@b5 recently mentioned they’d found a useful paper and built some interesting tools around this for Qri, so we should look into that.

**Comment by b5** [comment]
I've pointed @Mr0grog to this repo before, but our structured data differ is here: http://github.com/qri-io/deepdiff/ 

It's based on a paper that came out of the `xydiff` project: https://github.com/fdintino/xydiff
