### ISSUE TITLE
Incorporate Suggestions from IA folks on CDX API methods/tests

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#202]
The [tests that utilize Internet Archive’s CDX API](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/tests/test_ia.py#L6-L21) have recently become a bit flaky. @vbanos suggested a few improvements we should make here:

1. Add retries. [We already did this for some other Wayback APIs](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/internetarchive.py#L337-L338), but I guess not CDX, so we should incorporate those 😛  (Waiting to hear back on ideal retry/backoff/rate-limit values)

2. Use requests’s [`sessions` feature](http://docs.python-requests.org/en/master/user/advanced/#session-objects).

3. Use the [new?] [`pageSize` parameter](https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server#pagination-api) to test paging over a much smaller query on a URL that doesn’t have a bajillion captures (maybe we could use a date range to further limit it so it doesn't grow over time).

**Comment by danielballan** [comment]
> Waiting to hear back on ideal retry/backoff/rate-limit values

Just following up --- Did they get back on this? Worth pinging again?

**Comment by Mr0grog** [comment]
Ah, thank you for the reminder!

- 3 retries
- No suggestion on rate limit or backoff algorithm

**Comment by Mr0grog** [comment]
Ah, thank you for the reminder!

- 3 retries
- No suggestion on rate limit or backoff algorithm

(via @vbanos)

**Comment by Mr0grog** [comment]
@danielballan is checking into whether we should rely on some other CDX libraries for this (and whether they do the above) before actually implementing here.

Side note: in a client project, I wound up using the [`backoff` package](https://pypi.org/project/backoff/) for retry/backoff (it doesn’t do the initial rate limiting, though). It’s quite nice.

**Comment by Mr0grog** [comment]
After finally looking into it, I don’t think I understand `pageSize` very well (a `pageSize` of 1 does not mean one entry per page). But `limit` works great.

**Comment by danielballan** [comment]
Odd...

**Comment by Mr0grog** [comment]
Worked it out with them on Slack. It’s actually a the number of index chunks (with ~3000 items per index) that get used in the response, not the number of results (so `pageSize=1` basically means “no more than 3000 results per page”).

I need to submit a PR to their docs.
