### ISSUE TITLE
Can/should we be more lenient about decoding errors?

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#203]
One of our analysts is getting a unicode decoding error with this diff: 
https://monitoring.envirodatagov.org/page/a867fab2-52a2-4057-959d-9e24f6af5d0f/e8559c94-4a18-4637-ade2-e1f4828b6477..61cafbb0-9ba8-49d9-8a6b-5d28f6063ee0

Specifically, that’s a problem in this version: 
https://api.monitoring.envirodatagov.org/api/v0/versions/e8559c94-4a18-4637-ade2-e1f4828b6477

More specifically, the page declares itself to be UTF-8, but does in fact contain an encoding error. The diffing server currently does strict decoding by default (so it just throws an error in this case), but you can change that with the [`ignore_decoding_errors` query param](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/diffing_server.py#L251-L253)… except the UI never actually uses that param.

1. Should the UI always set this to `true`? (Or should we instead default it to `true` instead of `false` here on the processing side? Or something else?)

2. When we ignore errors, we totally ignore them. Should we instead do like most browsers do and replace them with `U+FFFD` (�)? That *should* mean just setting `errors='replace'` instead of `errors='ignore'` [when we actually decode the bytes](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/diffing_server.py#L205-L206)
    - Should we *also* include information about the fact that there was an error decoding in the response envelope in this case, even if it wasn’t a fatal error? e.g. something like:

        ```py
        # In `_decode_body`:
        try:
            return response.body.decode(encoding, errors='strict'), None
        except UnicodeError as error:
            # In the calling function, we'd add the second return value to the response envelope
            return response.body.decode(encoding, errors='replace'), error
        ```

/cc @danielballan

**Comment by Mr0grog** [comment]
What about changing the default vs. modifying the UI to always set `ignore_decoding_errors` to true?

**Comment by danielballan** [comment]
I'm having second thoughts on the `return value, error` matters. That's very JavaScript-y; I don't think I've ever seen it in a Python library. It's also pretty limited information: we'd learn about the _first_ decoding error, but this mechanism wouldn't tell us how many other decoding errors there might be.

I think I prefer:

```py
def f(..., decode_errors='strict'):
    ...
    return response.body.decode(encoding, errors=decode_errors)
```

with a `'strict'` default but `'replace'` passed in by the UI. This change is also backward-compatible: it does not alter the return type and it adds an optional parameter. I can implement the Python side if you are content with that, @Mr0grog.

**Comment by Mr0grog** [comment]
> I'm having second thoughts on the return value, error pattern. That's very JavaScript-y; I don't think I've ever seen it in a Python library.

I’ll definitely agree this very common (other than in Go, where it’s all over the place, but that’s because you should generally not panic in Go, like in C/C++/ObjC), but it’s certainly not any more JavaScripty that it is Pythonic. Anyway, how else would we get back information about the error alongside the decoded string? (Other than returning an object or dict, which seemed to me like unnecessary overhead.)

> It's also pretty limited information: we'd learn about the first decoding error, but this mechanism wouldn't tell us how many other decoding errors there might be.

I don’t think I’m following. The decoding here happens in [`_decode_body(response, name, ignore_errors)`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/811f701842d2f442ef4f5ffe09772ef0c2298d8b/web_monitoring/diffing_server.py#L202-L210), where I don’t think it would make sense for there to ever be more than one error.

What I was suggesting here was that, if you are “ignoring” errors, we’d pass back any errors that did occur as a second return value so that all the errors that happened could be collected and returned in the end response. The only real change there is that we’d now get back that error information instead of completely dropping it. (When not ignoring errors, this method would still throw just like it does today.)

> with a 'strict' default but 'replace' passed in by the UI.

I guess I was thinking about not changing the API contract at all here — the UI can **already** do

```
GET /some_diff?ignore_decoding_errors=true
```

…which equates to `decode(encoding, errors='ignore')` right now but we’d change to mean `decode(encoding, errors='replace')`. Are you thinking instead we’d change that query arg to be:

```
GET /some_diff?ignore_decoding_errors=ignore|replace|false
```

> This change is also backward-compatible: it does not alter the return type and it adds an optional parameter.

I think all the proposals on the table are more-or-less backward-compatible (assuming we’d count the above about changing the values for `?ignore_decoding_errors` as compatible). With point (2.1) I was meaning we’d change the response from:

```js
{
  "version": "<git hash>",
  "type": "<diff name>",
  "diff": "<diff content>"
}
```

to:

```js
{
  "version": "<git hash>",
  "type": "<diff name>",
  "diff": "<diff content>",
  "errors": ["<decoding error for a>", "<decoding error for b>", "<who knows what other errors we could put here in the future>"]
  // or "errors": {
  //   "a": ["<error>", "<error>", "<etc>"],
  //   "b": ["<error>", "<error>", "<etc>"]
  // }
  // or however is best to structure this ¯\_(ツ)_/¯
}
```

**Comment by Mr0grog** [comment]
Here’s a quick sketch of what I was thinking: https://github.com/edgi-govdata-archiving/web-monitoring-processing/compare/203-encoding-errors-sketch

**Comment by Mr0grog** [comment]
Wow, I’m suddenly realizing the item I meant to be a footnote (should we also find a way to surface the error that was ignored) probably confused the whole question :P

**Comment by danielballan** [comment]
I'm at least equally responsible for the divergence. Let me focus on one point that seems important to the API design, to me.

> The decoding here happens in `_decode_body(response, name, ignore_errors)`, where I don’t think it would make sense for there to ever be more than one error.

Doesn't the `.decode` method error out on the first character that it can't decode? If that problem is resolved, might their be other characters later on in the body that it also can't decode? That's what I'm getting at, and why I'm suggesting that returning "just the firs error" is maybe not that useful on the UI side since you can't interactively debug.

**Comment by danielballan** [comment]
> Another client might support some fancier inspection and interactive use. But if we’re not worried about that, I actually think the answers to all the questions here are really clear [...]

Let's go with that. I'm concerned about keeping the underlying diffing functions reusable/generic and un-coupled from the Tornado server and the UI. I'm less concerned about keeping the Tornado server and the UI decoupled from each other.

**Comment by Mr0grog** [comment]
Ok!
