### ISSUE TITLE
Package all the dependencies for conda.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#220]
Nothing is particularly hard to compile, but conda packages are convenient and fast, especially as these projects don't ship wheels.

**Comment by Mr0grog** [comment]
This was an outgrowth of #219, right? I was deploying the last few PRs and thought I would switch over the live servers to your newer deploy instructions using `environment.yml`, but realized two things:

1. `environment.yml` is missing version specifiers, which I think makes it a non-starter for a production service. I was going to add them, but…

2. I ran into the same cython issue as @jsnshrmn. Should we add it to the environment file for now, or should I just keep the servers using the old-style deployment for now?

**Comment by Mr0grog** [comment]
(Basically, what should we do for now until you are able to address this issue?)

**Comment by danielballan** [comment]
Stick to the old-style deployment.

We don't want to maintain the pins in two places. I think my original post was from before we pinned versions in requirements.txt. Now that we do that, I think the best way forward is **deploy** from `master` and use pip/venv/requirements.txt. For **interactive use** by analysts, who will get the best benefit from conda, roll actual releases of the package, and produce a proper conda package, which can reflect the version pinning from requirements.txt.

**Comment by Mr0grog** [comment]
👍 I will work up a PR to remove use of the `environment.yml` file from `deploy.md`, then.
