### ISSUE TITLE
Update to Circle 2.0.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#221]
Circle 1.0 is [sunsetting on 31 August](https://circleci.com/blog/sunsetting-1-0/).

**Comment by Mr0grog** [comment]
This already happened in #182. You were looking at a branch based on a super-out-of-date commit.

**Comment by danielballan** [comment]
Hah. I thought I remembered this coming up, searched our issues, but foolishly restricted my search to _open_ issues.
