### ISSUE TITLE
Make tests runnable without credentials.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#222]
Currently, a new contributor's PR will error on Circle because they will be missing the env vars necessary to run some of them. I think we discussed fixing this through some combination of VCR and, if necessary, `pytest.skip`.

**Comment by Mr0grog** [comment]
Uh, this happened in #186. The only reason it should try and look up env vars is if it can’t find a fixture and needs to download it. But it doesn’t appear as though there are any missing fixtures: https://github.com/edgi-govdata-archiving/web-monitoring-processing/compare/ee42eefc90ffe2f84d91ff6659dcc96b3d903d70...master

**Comment by Mr0grog** [comment]
Closing this. The problem that spawned this in #219 is just because that branch based on really old code.
