### ISSUE TITLE
Infer local file type from extension

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#231]
See https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/88#discussion_r208711145

**Comment by Mr0grog** [comment]
To summarize: when loading a `file://` URL in the diffing server, we assume the content is `application/html` (which is not even a correct mime-type; it should be `text/html`) and that it is UTF-8 encoded: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/33e99ee686c87df0254ef071a53d7c74dda1e457/web_monitoring/diffing_server.py#L136-L139

That’s obviously not correct all the time (e.g. we’d like to support PDFs, see #162, edgi-govdata-archiving#issues/36). We should do our best to infer the correct `Content-Type` header based on the file’s extension.

Python has a built-in module for this: https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type

There are also tools on PyPI like [mimelib](https://pypi.org/project/mimelib/) and public databases of extension ↔︎ mime type mappings: https://github.com/jshttp/mime-db

**Comment by Mr0grog** [comment]
Oops, this should have been closed with #457!
