### ISSUE TITLE
API call issue in Page Freezer Python Module

### ISSUE THREAD

**Issue by janakrajchadha** [edgi-govdata-archiving/web-monitoring-processing#24]
Hi, I tried running the PageFreezer ipython notebook on my machine and faced some issues.
The uploaded notebook already shows a key error when a request is sent.
https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/page_freezer_python_module/PageFreezer.ipynb

I tried debugging the issue and realised that the API call does not return the expected result.

![image](https://cloud.githubusercontent.com/assets/13016251/24087590/d61a4376-0d46-11e7-8c68-54dd4b2d9ccd.png)

I'm trying to figure out the details of the issue.
If someone has an idea of what the problem could be, please take a look.
@dcwalk , can someone help me with this?

**Comment by dcwalk** [comment]
I'm thinking it is one of two (probably both) things:
- An API key isn't being used (it doesn't look like it was in the original notebook... I'm seeing `api_key = ''`)
- Check the path of the diffs, in the original notebook the old repo name `pagefreezer-cli` is showing

If I recall correctly @danielballan and others revoked/renewed the API keys recently so maybe also communicate with them to ensure you have a set for testing?

**Comment by danielballan** [comment]
@WestleyArgentum I'll send you the API key on Slack.

**Comment by janakrajchadha** [comment]
@dcwalk 
Yeah, I did notice the missing api key.
As for the path, I was trying to compute the difference of the examples in the new repo. So, I don't think that was a problem.

@danielballan - Can I get access to the API keys or is it only for members?

**Comment by danielballan** [comment]
@janakrajchadha Any contributor can have it, we just can't post it publicly of course. Sent via Slack.

**Comment by WestleyArgentum** [comment]
Just seeing this, @danielballan thanks for the api key, I am interested in trying to run this, but is there something I should be doing to help this right now or @janakrajchadha did that fix your issue?

**Comment by janakrajchadha** [comment]
@WestleyArgentum That did get me the desired query result. However, I did face a few more issues in the rest of the notebook and I have fixed most of them. I'm still trying to fix a couple of them.
