### ISSUE TITLE
Add version endpoint to diff server

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#256]
I think it might be useful to add a `GET /version` endpoint to the diff server. That would return the version (or some hash of the source?) of the service that is running. Alternatively, `GET /info` or some similar name if we can think of other data besides version worth surfacing.

In the DB API, we currently have a config var referencing the last updated time of the diff server so we know to expire cache entries of the diff results. It would be pretty slick if we had the ability to simply poll the diff server every so often so the DB could auto-update this info. This might be especially useful as more folks start using the service (e.g. Wayback).

There are probably other useful cache features we could support, too:
- Support ETag headers (maybe a hash of `path + query + version`?)
- Have a cache built in (probably via Redis) at this level, instead of requiring someone to build it in a proxy/translation layer in front of this service (downsides: more complexity in this service, locking people in to one or a few cache implementations)
- ?

…but I think this endpoint would be useful regardless.

Any thoughts @danielballan @jsnshrmn @vbanos?

**Comment by danielballan** [comment]
> Alternatively, GET /info or some similar name if we can think of other data besides version worth surfacing.

Maybe how long the server has been running? The list of differs supported, which we currently expose at `/`?

> Support ETag headers (maybe a hash of path + query + version?)

This was new jargon to this scientific software programmer. Seems like a very good idea!

> Have a cache built in (probably via Redis) at this level, instead of requiring someone to build it in a proxy/translation layer in front of this service (downsides: more complexity in this service, locking people in to one or a few cache implementations)

As long as `dict` and `functools.lru_cache` are available options, sure. I expect we can do this in such a way that people adding a new cache implementation is an easy lift for anyone who feels "locked in" by whatever we choose.

**Comment by Mr0grog** [comment]
> > Alternatively, GET /info or some similar name if we can think of other data besides version worth surfacing.
> 
> Maybe how long the server has been running? The list of differs supported, which we currently expose at `/`?

Hmmm, this makes me think we should just revise the `/` endpoint to be an object instead of an array and add version there:

```
GET /

{
  "version": "0+untagged.502.g75fa29c",
  "diff_types": ["html_token", "links", ...]
}
```
