### ISSUE TITLE
Content is getting cut off in the HTML diff

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#259]
In this diff, content from the March 14th snapshot is not showing up in the resulting diff data:

https://monitoring.envirodatagov.org/page/77dae44d-6ed1-4ead-9a8a-d5bcd60a7655/cf6e6ba5-0a8c-47fc-95fb-9a13bc504d5b..f09d4030-b1f2-4848-a4d2-6fa3ba25b910

**Comment by Mr0grog** [comment]
Dollars to donuts this is an LXML parsing error, but need to find time to look at it.

**Comment by shapironick** [comment]
+1 to idiom learning through stalking our git hub 

Sent on the move

**Comment by Mr0grog** [comment]
Nope, this parses fine. It’s something to do with how we are putting the DOM back together afterward. This is a painfully different diff.

**Comment by Mr0grog** [comment]
OK, this is a somewhat involved mess, and part of the legacy bits from lxml.htmldiff that we haven’t *entirely* shrugged off. When we do an HTML diff, we:

1. Parse the two HTML strings with BeautifulSoup so we can manipulate them more easily: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/2367454ed5156e06cbce99d01f5d31f26c3649e9/web_monitoring/html_diff_render.py#L261-L264

2. Do some work on that content, and diff just the *bodies*: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/2367454ed5156e06cbce99d01f5d31f26c3649e9/web_monitoring/html_diff_render.py#L277

3. Convert those bodies *back to strings* for the lower-level bits we inherited from lxml but have not yet updated to chew on (!): https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/2367454ed5156e06cbce99d01f5d31f26c3649e9/web_monitoring/html_diff_render.py#L391

4. Then the tokenizer does a little cleanup before feeding the HTML string to etree to parse via `fragment_fromstring()`: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/2367454ed5156e06cbce99d01f5d31f26c3649e9/web_monitoring/html_diff_render.py#L593-L604

5. Then we generate the tokens to diff from that.

The issue at heart here is that LXML’s parser chokes on some of the content in this document during step 4. Specifically, the page has a script:

```html
<script type="text/javascript">
	/*<![CDATA[*/
	
	eds2_2(function ($) {var $articleContentWrapper = $('#dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle');$articleContentWrapper.on('click', 'a[rel^="ednSmbLight"]', function () {var $clicked = $(this),$smbItems = $('a[rel^="ednSmbLight"]'),i = 0,lightboxItems = [],lightboxOptions = {openAt: 0,cssClass: 'modern'};$smbItems.each(function () {if (this == $clicked[0])lightboxOptions.openAt = i;lightboxItems.push($(this).data('smbdata'));i++;});new SmbLight_1(lightboxItems,lightboxOptions);return false;})});
	
	
	
						eds2_2(function ($) {
							$('#dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle_edn_printButton').on('click', function (){
								var prtContent = document.getElementById('dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle'),
									spacelessTitle = 'Study shows ocean acidification is two-front assault on coral reefs'.replace(/\s/g, '_'),
									WinPrint = window.open(this.href, spacelessTitle, 'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=450,height=250');

								WinPrint.document.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">");
								WinPrint.document.write("<html><head><title>Study shows ocean acidification is two-front assault on coral reefs</title><link rel=\"stylesheet\" type=\"text/css\" href=\"https://research.noaa.gov/DesktopModules/EasyDNNnews/Templates/_default/Ozone/Ozone.css\"/></head><body>");
								WinPrint.document.write("<div class=\"news Ozone_Style_custom_sihdpmiutwg eds_style_custom_sihdpmiutwg eds_subCollection_news eds_news_Ozone eds_template_Details_Article_Research eds_templateGroup_detailsArticleDefault eds_styleSwitchCriteria_module-1768 eds_print\">")
								WinPrint.document.write(prtContent.innerHTML);
								WinPrint.document.write("</div></body></html>");
								WinPrint.document.close();
								WinPrint.focus();

								setTimeout(function () {
									WinPrint.print();
								}, 500);

								return false;
							});
						});
	// ...trimmed here for brevity!
```

But after parsing, it ends in the middle of the last `WinPrint.document.write()` call:

```html
<script type="text/javascript">
	/*<![CDATA[*/

	eds2_2(function ($) {var $articleContentWrapper = $('#dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle');$articleContentWrapper.on('click', 'a[rel^="ednSmbLight"]', function () {var $clicked = $(this),$smbItems = $('a[rel^="ednSmbLight"]'),i = 0,lightboxItems = [],lightboxOptions = {openAt: 0,cssClass: 'modern'};$smbItems.each(function () {if (this == $clicked[0])lightboxOptions.openAt = i;lightboxItems.push($(this).data('smbdata'));i++;});new SmbLight_1(lightboxItems,lightboxOptions);return false;})});



						eds2_2(function ($) {
							$('#dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle_edn_printButton').on('click', function (){
								var prtContent = document.getElementById('dnn_ctr1768_ViewEasyDNNNewsMain_ctl00_pnlViewArticle'),
									spacelessTitle = 'Study shows ocean acidification is two-front assault on coral reefs'.replace(/\s/g, '_'),
									WinPrint = window.open(this.href, spacelessTitle, 'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=450,height=250');

								WinPrint.document.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">");
								WinPrint.document.write("<html><head><title>Study shows ocean acidification is two-front assault on coral reefs</title><link rel=\"stylesheet\" type=\"text/css\" href=\"https://research.noaa.gov/DesktopModules/EasyDNNnews/Templates/_default/Ozone/Ozone.css\"/></head><body>");
								WinPrint.document.write("<div class=\"news Ozone_Style_custom_sihdpmiutwg eds_style_custom_sihdpmiutwg eds_subCollection_news eds_news_Ozone eds_template_Details_Article_Research eds_templateGroup_detailsArticleDefault eds_styleSwitchCriteria_module-1768 eds_print\">")
								WinPrint.document.write(prtContent.innerHTML);
								WinPrint.document.write("</div></body></html></script></div></div></div></td></tr></tbody></table></td></tr></tbody></table></div></div></div></div></div></div></div></div></div></div></div></div></form></div>
```

It *might* be possible to fix by using html5-parser again here:

```py
# Instead of fragment_fromstring(html, create_parent=True)
return html5_parser.parse(html, treebuilder='lxml', return_root=True)
```

…but otherwise we just need to do the work of removing this double-parsing step, which obviously is something we should be doing anyway. It’s just a lot more involved and error-prone.

---

Some helpful bits…

URL of the raw “a version” body: https://edgi-wm-versionista.s3.amazonaws.com/versionista2/74300-6219592/version-14975479.html

URL of the raw “b version” body: https://edgi-wm-versionista.s3.amazonaws.com/versionista2/74300-6219592/version-17377697.html

Get the “deletion” side of the HTML diff for testing:

```sh
> curl 'http://localhost:8888/html_token?a=https%3A%2F%2Fedgi-wm-versionista.s3.amazonaws.com%2Fversionista2%2F74300-6219592%2Fversion-14975479.html&b=https%3A%2F%2Fedgi-wm-versionista.s3.amazonaws.com%2Fversionista2%2F74300-6219592%2Fversion-17377697.html&include=all' | jq '.deletions' --raw-output
```

**Comment by Mr0grog** [comment]
D’oh, it’s not the second parse, it’s the `cleanup_html` call, which uses some poorly considered regexes: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/2367454ed5156e06cbce99d01f5d31f26c3649e9/web_monitoring/html_diff_render.py#L606-L621

I can at least feel good that that function is also inherited from `lxml` but it still should have been a more obvious issue. 🙃

`cleanup_html()` does a few things:

- Finds `<body>...</body>` if present and unwraps it so we have just its contents as a string **(this is the core problem)**. We should see if we can eliminate the need for this altogether, since we already effectively do all the kinds of HTML basic structure validation much earlier on now.

- Finds `<ins>` and `<del>` tags and removes them. Ideally, we shouldn’t be doing that at all, but this has been an old discussion and the algorithm needs lots of fixing to get around that: https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/69#issuecomment-321424897 Instead, we can actually just move this up a few levels and remove them from the original BeautifulSoup representation before we even get to this re-parsing step.
