### ISSUE TITLE
Support invalid encoding `iso-8559-1`

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#310]
In https://sentry.io/environmental-data-governance-/diffing-server/issues/755653660/, we have some content that claims to be encoded as `iso-8559-1`. That’s a typo for `iso-8859-1` (i.e. ASCII or latin-1).

Since `iso-8559-1` is actually a clothing size standard, I think we can safely map this to the correct encoding :)

**Comment by jsnshrmn** [comment]
👍 I like the idea of attempting ASCII decoding as a last ditch, dumb thing to try (when we're sure something isn't binary) before giving up.
