### ISSUE TITLE
Document PR shortcodes in Contributing Guidelines/Issue Template

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-processing#48]
I dig @danielballan 's shortcodes for PRs, but also am pretty sure I don't know what some of them mean. Maybe we could add an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) OR add them to the project-specific guidelines?

If @danielballan chimes in with a list of 'em this could be a good `first-timer` issue :)

**Comment by danielballan** [comment]
Sure thing! I just picked these up from contributing to pandas, but I found an official list of this in [this section of the scipy contributor docs](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message).

> API: an (incompatible) API change
BLD: change related to building
BUG: bug fix
DEP: deprecate something, or remove a deprecated object
DEV: development tool or utility
DOC: documentation
ENH: enhancement
MAINT: maintenance commit (refactoring, typos, etc.)
REV: revert an earlier commit
STY: style fix (whitespace, PEP8)
TST: addition or modification of tests
REL: related to releasing

I also use:

CI: Fixes that only touch Circle-CI or Travis-CI config (not actual project code)
FIX: synonym for BUG

**Comment by Mr0grog** [comment]
Electron also does something similar, but using emoji: https://github.com/electron/electron/blob/master/CONTRIBUTING.md#git-commit-messages

**Comment by titaniumbones** [comment]
Man those abbreviations are a lot clearer than the emoji!

On May 28, 2017 5:24:51 PM EDT, Rob Brackett <notifications@github.com> wrote:
>Electron also does something similar, but using emoji:
>https://github.com/electron/electron/blob/master/CONTRIBUTING.md#git-commit-messages
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/48#issuecomment-304541375

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcwalk** [comment]
Copy pasting from @Mr0grog's above:

* Consider starting the commit message with an applicable emoji:
  * :art: `:art:` when improving the format/structure of the code
  * :racehorse: `:racehorse:` when improving performance
  * :non-potable_water: `:non-potable_water:` when plugging memory leaks
  * :memo: `:memo:` when writing docs
  * :penguin: `:penguin:` when fixing something on Linux
  * :apple: `:apple:` when fixing something on macOS
  * :checkered_flag: `:checkered_flag:` when fixing something on Windows
  * :bug: `:bug:` when fixing a bug
  * :fire: `:fire:` when removing code or files
  * :green_heart: `:green_heart:` when fixing the CI build
  * :white_check_mark: `:white_check_mark:` when adding tests
  * :lock: `:lock:` when dealing with security
  * :arrow_up: `:arrow_up:` when upgrading dependencies
  * :arrow_down: `:arrow_down:` when downgrading dependencies
  * :shirt: `:shirt:` when removing linter warnings

**Comment by mhucka** [comment]
FWIW I agree with @titaniumbones on this: the emoji are cute and save 3 chars (5 in the case of MAINT), but many of the emoji associations seem arbitrary and IMHO people are much more likely to have to look up their meanings.

**Comment by Mr0grog** [comment]
FWIW, I wasn’t trying to make a competing proposal, just illustrating another major project that has found tagging commits useful ;)

That said… I would argue that for non-native English speakers, the emoji and no less clear (and sometimes more clear). My experience with international colleagues in the past has been that abbreviations do not work *remotely* as well for even fluent non-native speakers as they do for native speakers (with the sole exception of *extremely* common ones like “doc”—the rest are no more clear that if you just used single letters). Obviously that’s really anecdotal, but my general lesson through painful experience has been complete words or it generally may as well be abstract symbols.

Anyway! With the above, I would throw my hat in the ring for full word tags: “[doc] message” / “[test] message” / “[api] message” / etc. or “DOC: message” / “TEST: message” / “API: message” / etc.

That said, I think all of these work. No matter what we choose, we should use them across all the `web-monitoring*` repos and we need a PR to put info about them in https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/CONTRIBUTING.md (and maybe the contributing doc in all the other `web-monitoring-*` repos, too).

**Comment by mhucka** [comment]
@Mr0grog That actually does seem quite likely – I haven't tried to use these with my international colleagues, but I can imagine abbreviations would be more difficult for non-native English speakers. And now that I look at the abbreviations and start trying to use them in actual commit messages, I'm beginning to see redundancies, and in addition, it seems like both the SciPy ones and the emoji mix concepts: some of them are about types of entities (code, test system, build system) and others are about actions (adding, fixing, enhancing).

So based on that, my preference would be either to give up on this idea altogether, or find a small (no more than 7) subset of short full-word terms, and make them only about _either_ actions _or_ entities, and tell people to use the text of the message to explain the rest (i.e., if it's an action, then make the message text say what the entity is, or conversely, if it's an entity, then the commit message should explain the action). Here's a candidate subset if we make it about actions:

**FIX**: fix a bug or other issue
**NEW**: implement/add a new feature or new documentation (subsumes ENH)
**REVERT**: revert a previous change or behavior
**REVISE**: code or doc change that is not a bug fix or new feature (subsumes DEP, MAINT)
**RELEASE**: release a version

Sample messages:

"REVISE: Remove very out-of-date docs"
"NEW: Add check to build sys for Python version to help confused Python 2 users"
"REVISE: Update README development status and install instructions"

**Comment by dcwalk** [comment]
I'm removing first timer because this has become a little more muddled -- 

I'd favour using full words or common shortcuts ("Docs") and even augmenting with an emoji (we can always have them at the ready in the github issue template after all, making it a copy-paste exercise rather than a typing one.

That said, I leave it to the web monitoring people to sort out what is best!
