### ISSUE TITLE
Create a stash of interesting PageFreezer diff responses

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#49]
Since querying PageFreezer's public API takes ~10 seconds, it would be useful to build an archive of PageFreezer responses for analysis. I'm picturing a script in this repo that, when run, generates a ZIP archive. We would distribute that archive as a build product, not something that we keep in git itself.

Two months ago we talked about pulling classification information from the monitoring team's spreadsheets into our efforts, but it was ungoing a QA review. Has that review concluded? attn @trinberg @ambergman @mayaad 

Related issues: https://github.com/edgi-govdata-archiving/web-monitoring/issues/16, https://github.com/edgi-govdata-archiving/web-monitoring/issues/30, https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/6

**Comment by trinberg** [comment]
The most progress we've made on classifications is on page 3 of this doc: https://docs.google.com/document/d/1Dba3suzUrves36g0SnTKAnwzNqvePnoRq_-YhLutN2g/edit

Note that this is certainly NOT the final version and the three sections: 1)  
Page Pertains To; 2) Change Content Pertains To; and 3) Type of change - will all be amended and built out as we work on this more. I don't want to entrench anything final, but if this helps you with the sprint, then it makes sense to use this. I'm also happy to be on call or discuss any of these categories in more depth. I'm not up-to-speed on the topic of the sprint and could provide better context or spend more time on the classifications if it's helpful

**Comment by danielballan** [comment]
Notes from a phone conversation with @trinberg:

Terms:
* "substantial" = a big change that might or might not be of interest to EDGI
* "significant" = a change that is of interest to EDGI (but does not necessarily rise to the level of generating a report, could be a random mistake)

There is a list of 300-400 urls where the change between the latest snapshot and the first snapshot is substantial but maybe not significant. The analysts don't classify the change in much detail with respect to the content of the change: they describe it without reference to the domain-specific content, such as if a link was changed or an image was changed.

In a new, more detailed pass at these 300-400 urls, the monitoring team has applied a more specific analysis ("theme analysis") focusing on three themes. (See the Google doc in the previous comment for details.):
* What is the content of the page (irrespective of the change)?
* What is the specific content of the change (climate, energy, economy, etc.)?
* What is the type of change: page deleted, text changed, link removed?

As an aside, a major interest in the future will be annotating specific sections of pages, not the page as a whole. PageFreezer diffs can help with this. We should also talk to Klaxon again when we are ready to think about this.
 
I intend to make a stash of diffs (with associated classifications) from these 300-400 urls.
