### ISSUE TITLE
Experiment with other ways of computing diffs

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#5]
Ideally this work should match the interface of PF.

``f(html1: string, html2: string) -> dict`` where the output dict has the same keys as the PF result (or a superset of those keys)

**Comment by danielballan** [comment]
To elaborate a bit on the motivation here:

PageFreezer's diff outperforms a simple plain text diff by understanding the structure of HTML. We might be able to do even better by making more assumptions about the structure (especially for a specific subdomain) and by incorporating the information logged by volunteers manually examining diffs.

**Comment by mhucka** [comment]
I have some limited experiences writing Python code to scrape content for other projects, from which my impression is that it's very difficult to have a general way to ignore some HTML versus other.  It really seems like you need very targeted knowledge about the specific HTML structure used by a given site, and then can write code to look for (or ignore) particular pieces.

I've been trying to think of a better way of handling this, but so far all I've got is the following list of possible alternatives.

1. (Simplest but probably worst.) Strip all the HTML to leave just text. Diff that.

2. (More difficult and labor-intensive, but likely the most effective.) Have an extensible framework consisting of front-end detectors/processors that can recognize different CMS systems (WordPress, others). Have each such detector/processor/recipe massage the input to produce a common agreed-upon final form. This final form is what gets fed to the change detection system.

3. (Probably research-grade development.) Don't consider the HTML at all. Instead, take the rendered result, detect text regions, extract text (maybe using OCR), and compare those. I've actually seen some work along these lines, and could find the research papers again if needed.

**Comment by danielballan** [comment]
> I've actually seen some work along these lines, and could find the research papers again if needed.

We might finally be approaching the point where we could direct some volunteer interest at this problem, @mhucka. Could you post some references?

**Comment by danielballan** [comment]
I have split this issue into separate ones addressing suggestions (2) and (3) individually. We are now already doing suggestion (1) in production.
