### ISSUE TITLE
There is no file named .env.example

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring-processing#55]
Point 3 in [Installation instructions](https://github.com/edgi-govdata-archiving/web-monitoring-processing/#installation-instructions) says "Copy the script .env.example to .env and supply any local configuration info you need.". 

There is no file named `.env.example`.

**Comment by Mr0grog** [comment]
Isn’t that this file? https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/.env.example

**Comment by Mr0grog** [comment]
@KrzysztofMadejski let me know if you’re still not seeing that file, otherwise I’ll close this issue.

**Comment by KrzysztofMadejski** [comment]
I've had a few days old repo, it has been pulled in https://github.com/edgi-govdata-archiving/web-monitoring-processing/commit/de61f238422fd88e0c3eb3fb7cf27a2c9162fe47#diff-cbfd64a28982a1818f2b5f16e7f9d634. I'm closing it.
