### ISSUE TITLE
Extract signals from diff result

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#6]
Summary of ideas (copied from PROPOSALS.md from NYC event)

Per row:
* type of change
* contains date
* contains non-visible tag
* contains any tag
* contains number
* contains link tag
* total characters changed
* (maybe!) NLP metrics like "edit distance"

Per document:
* total characters changed
* history (timing) of changes

**Comment by Mr0grog** [comment]
This is pretty tightly tied in with #175 and edgi-govdata-archiving/web-monitoring-db#416. We should consolidate. (Or break apart into very concrete individual items.)

**Comment by Mr0grog** [comment]
Prioritizing this for myself to do the aforementioned consolidation/breakup.

**Comment by Mr0grog** [comment]
This is happening over on the [web-monitoring-task-sheets](https://github.com/edgi-govdata-archiving/web-monitoring-task-sheets/) repo.
