### ISSUE TITLE
Coordination with Python projects on the archiving side

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#61]
It might be nice to be consistent about packaging choices and technology choices, where it makes sense to do so. Here are points off the top of my head:

Currently, we:

* use a `requirements.txt` read by the `setup.py` to make dependencies discoverable

I plan to:

* use Circle-CI
* use versioneer to keep `web_monitoring.__version__`, the setup.py `version`, and git tag in sync with one another
* use sphinx for API documentation, possibly autogenerating the prose docs from Markdown pending more discussion

attn @jeffreyliu

**Comment by jeffreyliu** [comment]
disclaimer, my python background is mostly in scientific computing, so this is the first time I've written stuff for actual distribution, so my practices might not be the most kosher?

I've been using `requirements.txt` for replication of virtualenvs via `pip freeze > requirements.txt` which contain specific version numbers and then installation via `pip install -r requirements.txt`

my `install-requires` in `setup.py` looks like your requirements.txt in that it just includes the names of packages. [One difficulty I've run into](https://github.com/datatogether/archivertools/issues/1) is that `setup.py` doesn't seem to support installation from non-PyPI sources by default, and `--process-dependency-links` seems to be deprecated.

I'm on board w/ Circle-CI for deployment, and haven't used versioneer or sphinx before, but I'm down to use them for our sync/docs

**Comment by danielballan** [comment]
Haha, no worries, @jeffreyliu. My background is the same, but I've been pulled more fully into the software development side of things over the last two or three years.

You might like [the trick](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/setup.py#L21) in my setup.py because you only have to maintain the requirements.txt list in one place.

You might be able to solve your problem by putting a line like this in your requirements.txt:

```
    - git+https://github.com/YOUR_ORG/YOUR_PAKCAGE#egg=YOUR_PACKAGE_NAME
```

That requires git to be installed, but I don't think it requires `--process-dependency-links`.

**Comment by jeffreyliu** [comment]
Just as a sidenote, a line like
```
- git+https://github.com/YOUR_ORG/YOUR_PAKCAGE#egg=YOUR_PACKAGE_NAME
```
breaks if you use `read('requirements.txt').split()` because it splits on the whitespace between `- git+...`. Using `read('requirements.txt').splitlines()` avoids this.

Also, should it be `-e git+...` instead?

**Comment by danielballan** [comment]
Great suggestion with `splitlines`. I think the `-e` is only necessary if you want an editable checkout.

**Comment by Mr0grog** [comment]
@danielballan I think we’ve done all of this, right? Anything else that needs to happen here or should we close it?
