### ISSUE TITLE
Diff-match-patch seems to be working poorly

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#67]
This might just be that we need to twiddle the settings a bit, but we are getting pretty poor diff results from the current diff-match-patch library. In this example from the UI, we should *not* just have two big blocks. Also odd is that the defaults for this library and `go-calc-diff` are the same, but their results are very different:

![dmp-side-by-side](https://user-images.githubusercontent.com/74178/28443491-3191c470-6d6b-11e7-8200-6b23f3be358f.png)

Implementation in this repo on left, `go-calc-diff` on right.

I briefly tried switching to [`diff-match-patch-python`](https://pypi.org/project/diff_match_patch_python/), and it seems to get nice results. Check out the [`switch-to-dmp-python` branch](https://github.com/edgi-govdata-archiving/web-monitoring-processing/compare/switch-to-dmp-python).

**Comment by b5** [comment]
wow, that is odd. If switching out the package yields usable results I'd vote for just dropping that in & moving on. We're going to have to spend a bunch of time tuning & fiddling anyway

**Comment by Mr0grog** [comment]
Thanks. I think I’ll leave this over the weekend in case @danielballan is able to take a look and knows anything I don’t. If not, I’ll just merge that branch in on Monday.

**Comment by janakrajchadha** [comment]
@Mr0grog I had discussed this with @danielballan a few days back. I had found python libraries for it but I had never tried them together and tested the results. From what I have seen and read, `diff-match-patch-python` seems to be the better option. I'll take up this issue and get it done by Monday.

**Comment by janakrajchadha** [comment]
@Mr0grog I've added a few things on top of your changes. You can find them [here](https://github.com/janakrajchadha/web-monitoring-processing/blob/master/web_monitoring/differs.py). Please take a look and I'll create a PR if you think it's fine.

**Comment by janakrajchadha** [comment]
@Mr0grog Any comments on this?

**Comment by Mr0grog** [comment]
So sorry, I didn't see your first request for review. I think this makes sense to PR. Quick notes:

- I don’t think renaming the DMP functions to `d` and `d_b` makes sense here. It did before because we were creating an instance of an object. These are now just static functions, so this isn’t doing much besides obscuring the function call. (It also might make sense to just directly import the two functions we are using instead of asking for `diff_match_patch.diff`, for example)

- We should *probably* go back to making the result an array of tuples—it seems more technically correct and the array of arrays was really a quick coding mistake on my part. Not sure there’s any performance impact (if there is and it’s meaningful, go with whichever is better there).

- Any reason for:
  1. Not making the the time limit configurable (since it used to be) and
  2. Changing the default time limit from 2 seconds to 4?

- Please keep spaces between arguments (e.g. in `isinstance(a_text,str)`)

- I feel dumb for not reading the docs and even realizing there was a `counts_only` flag. We should just set that to false, which makes processing the result *way* easier!

**Comment by Mr0grog** [comment]
Oh, also: I *think* it’s generally frowned upon to use `&` instead of `and` for a boolean operation, since `&` is really intended to be a bitwise operator in Python (though it does work with booleans). I am not a Python style expert on this kind of thing, though.

**Comment by janakrajchadha** [comment]
All good points @Mr0grog.

- Yeah, renaming the functions doesn't make sense. I was just replacing the functions in the older code and I guess I didn't think this through. 😅 
- You're right. We should go back to array of tuples as we are dealing with the result of the diff and we don't want any mutations in that.
- 
  i. Removing the option to configure the time is just a mistake I made.
  ii. I changed the time to check if there was any change in performance in case of a big chunk of text and I just forgot to change it back once I realised that there wasn't any difference.

- I did write the code with `counts_only` set to false but that returns tags (`-`,`=`,`+`) which we aren't using ('-1','0','1') and I thought there was a reason you had written the tagging part yourself.

- Thanks for pointing out that last thing. At times things which just seem to work in Python are not technically correct and I've often faced issues where I've committed such a mistake because I would have read about it only if I had encountered an error. As long as I keep getting feedback, I think my mistakes will go on decreasing.

**Comment by janakrajchadha** [comment]
@Mr0grog I've made most of the changes. I've some updates on my other tasks as well. Once I've pushed my code (after just doing another check), I'll create a PR and inform you.

**Comment by Mr0grog** [comment]
Sounds perfect! 👍

**Comment by Mr0grog** [comment]
> I did write the code with counts_only set to false but that returns tags (-,=,+) which we aren't using ('-1','0','1') and I thought there was a reason you had written the tagging part yourself.

Nope, just my not reading the docs. Pretty much all the extra work I was doing was to figure out what string to use for the second item in the `(operation, string)` pair. If we use `counts_only=False`, then we can:

```python
diff_codes = {'=': 0, '-': -1, '+': 1}
raw = diff(a_text, b_text, checklines=False, timelimit=TIMELIMIT, cleanup_semantic=True, counts_only=False)
result = [(diff_codes[change[0]], change[1]) for change in raw]
```

We could probably also just change the API to use the exact result from `diff()`; the only consumer right now is the UI, which isn’t really shipping yet.

**Comment by janakrajchadha** [comment]
I don't think we should change the API to use the result from `diff()`, as these tags are only used by `diff-match-patch`. I think it's better if we use `(0,-1,1)`.

**Comment by janakrajchadha** [comment]
@Mr0grog I've made the changes. Take a look [here](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/68/commits/c14af5d9e7dd7b5af345196f38767867359b14aa).

**Comment by janakrajchadha** [comment]
@Mr0grog I think this is done. I would have closed this but looks like I don't have the right permissions.

**Comment by Mr0grog** [comment]
FYI, next time, if you include `fixes #67` (or whatever the relevant Ng number is) in one of the commit messages in your PR, this will close automatically when the PR is merged.

**Comment by Mr0grog** [comment]
For example: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/105/commits/6a96301b6eab60dc74484ae8752a59cfdadc46f5

More info: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by janakrajchadha** [comment]
@Mr0grog Thanks for the helpful tip! 😄
