### ISSUE TITLE
Add HTML diff for rendering

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#69]
The most common diff view that analysts use in Versionista is the side-by-side highlighted diff:

![screen shot 2017-07-26 at 5 44 00 pm](https://user-images.githubusercontent.com/74178/28649532-6d530a1e-722a-11e7-93e8-6d0981d2f7d9.png)

It’s often hard to tell exactly what is meaningfully changing from a content perspective when looking at a source code diff—especially if, like many of the analysts, you are not a web developer who knows HTML really well. This view makes it very clear what is changing and how it relates to the page as a user sees it.

The main idea here is to be able to generate two versions of the HTML page—one with removed content highlighted (probably wrapped in `<del>` tags) and one with added content highlighted (probably wrapped in `<ins>` tags). This means the diff needs to be structurally aware and not start an insertion or deletion in the middle of a markup for a tag.

For example, it should handle scenarios like:

```
<a href="/careers/interns-post-docs.html">Interns & Postdocstoral<br/>Opportunities</a>
                  --------                ----------       -+++++++++++++++++++++++
```

Which can’t really be rendered as a web page because the diff intersects with HTML code. Instead we should get something like:

```
<a href="/careers/interns-post-docs.html">Interns & Postdocs</a><a href="/careers/post-docs.html">Postdoctoral<br/>Opportunities</a>
----------------------------------------------------------------++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

Or, even fancier, data about non-visual changes included (Versionista isn’t this fancy, but this would really help analysts):

```
<a href="/careers/interns-post-docs.html" data-wm-change="Link URL changed from '/careers/interns-post-docs.html' to '/careers/post-docs.html'">Interns & PostdocsPostdoctoral<br/>Opportunities</a>
                                                                                                                                                ------------------++++++++++++++++++++++++++++++
```

**Comment by janakrajchadha** [comment]
I think once we've checked a few results from `diff-match-patch`, we can build on top of its result to add the `<ins>` or `<del>` tags.

**Comment by Mr0grog** [comment]
Ok. I suspect this might be better served by an entirely different diffing algorithm that diffs node trees. Trying to parse your way through the output from diff-match-patch and determine what parts are intersecting in what way with HTML elements will certainly not be straightforward.

**Comment by Mr0grog** [comment]
Relatedly, here are a couple good test cases for making sure this sort of diff does not wind up with weird, erroneous non-changes being highlighted. These are places where Versionista’s version of this diff screws up, sent to my by the analyst team:

https://versionista.com/78483/6538911/ (compare [May 25, 2017 2:59 PM with Jul 22 2017 9:19 AM](https://versionista.com/78483/6538911/12215396:11485773))

https://versionista.com/78483/6538916/ (compare [Apr 13 2017 1:08 PM with Jul 22 2017 11:50 AM](https://versionista.com/78483/6538916/12216360:10866062/))

![screen shot 2017-07-28 at 11 26 12 am](https://user-images.githubusercontent.com/74178/28731149-9b4cf7fa-7387-11e7-8964-916ce5d908cb.png)

**Comment by janakrajchadha** [comment]
@Mr0grog After going through a few links, here are some of the possible implementations of the algorithm you were talking about:
1. http://lxml.de/api/lxml.html.diff-pysrc.html#htmldiff
2. https://pypi.python.org/pypi/html-tree-diff/0.1.2
3. https://www.logilab.org/859
Only the first one looks recently updated. The other two haven't been updated in a while.
Perhaps you can take a look and make sure that we're on the same page here as I dive deeper into the documentation of each one of these.

**Comment by janakrajchadha** [comment]
@Mr0grog Did you take a look at the links I've posted above?
Any comments?

**Comment by Mr0grog** [comment]
No, I have not had time to do so.

**Comment by janakrajchadha** [comment]
@Mr0grog Do we want a side-by-side rendering like Versionista's or would a single page render with the proper tags work?

**Comment by mhucka** [comment]
Based on the telecon earlier today with @suchthis and @danielballan, it sounds like lxml will be what's used. Therefore, I think [@janakrajchadha 's question for @Mr0grog](https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/69#issuecomment-319138072) above has been answered.

Related: [PR #76 in web-monitoring-processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/76#issuecomment-320718303)

**Comment by Mr0grog** [comment]
FWIW, I don’t think the fact that we are using lxml for extracting text need constrain us to also use it for diffing HTML trees. That said, it’s a reasonable reason for starting there. FWIW, it looks like `html-tree-diff` may be lxml-based as well (it is a dependency, at least).

> Do we want a side-by-side rendering like Versionista's or would a single page render with the proper tags work?

Versionista supports both and analysts pretty reliably prefer side-by-side from my understanding, so that’s what we want to support (but we should ask them).

That means for either the `lxml.html.diff` or `html-tree-diff`, you’ll have to reach into the internals a bit, since both their public interfaces spit back a single HTML page with `ins` and `del` elements embedded together. `html-tree-diff` looks like it has a nice [`Differ` class in `htmltreediff.diff_core`](https://github.com/christian-oudard/htmltreediff/blob/master/htmltreediff/diff_core.py#L28) that you’d want to use (see how it’s used internally [here](https://github.com/christian-oudard/htmltreediff/blob/master/htmltreediff/html.py#L12-L30) and [here](https://github.com/christian-oudard/htmltreediff/blob/master/htmltreediff/changes.py#L33-L46)); `lxml.html.diff` looks like you’d want to tokenize and then call directly to `InsensitiveSequenceMatcher` the same way [`htmldiff_tokens`](http://lxml.de/api/lxml.html.diff-pysrc.html#htmldiff_tokens) does. Having trouble getting a clearer understanding of the logilab library.

**Comment by janakrajchadha** [comment]
@Mr0grog I'm not too keen on using `html-tree-diff`, primarily because it hasn't been updated in a long time. Also, we will have minimal or perhaps no support(developer/community) in case we face any issues. `lxml`, as their [site](http://lxml.de/) suggests, is a Python binding for known C libraries and seems to be quite popular (2 million downloads, as mentioned on the website). I have succeeded in creating a single page diff(single page) render. It seems to have solved the issue of false positives, which were present in the Versionista diff. I'm gonna spend time now diving deeper into the internal code to write more efficient and cleaner code. Also, I'll also start on the side-by-side render issue after taking the analyst team's opinion in the dev call on Wednesday. Sounds good?

**Comment by Mr0grog** [comment]
Sounds like some good arguments to me.

> Also, I'll also start on the side-by-side render issue

Just to be clear, you don’t necessarily need to render two pages; you just need to be able to return the content and changes in a format the front-end can read and render. What we get from the current source and text diffs can easily be rendered side-by-side already, for example.

> after taking the analyst team's opinion in the dev call on Wednesday

This call is probably not a good place for that question—from the analyst side, it’s mostly only been @trinberg and @ambergman; most analysts don’t show up. You should ask this in the analysts’ Slack channels or at the analyst meeting Thursday night.

**Comment by janakrajchadha** [comment]
>you just need to be able to return the content and changes in a format the front-end can read and render
I'm sorry, I didn't quite get you. Are you saying that our ui already has an option for a side-by-side render? (I thought analysts were only using Versionista for viewing diffs)
If yes, can you direct me to the format it requires the changes to be in?

>You should ask this in the analysts’ Slack channels or at the analyst meeting Thursday night.
Alright!

**Comment by Mr0grog** [comment]
> Are you saying that our ui already has an option for a side-by-side render?

No, just that it is trivial to add with no back-end changes.

That's because the diff report is a structured representation and not an opaque blob of HTML. I think it's important that all our diffs work this way so that people focused on UI and interaction work are free to experiment with more innovative ways of displaying and navigating the diffs without needing to run all the various parts of our tech stack locally. For example, our text and source diffs are really simple right now, but the data format allows us to do fancier stuff on the front end, like the way GitHub diffs can progressively expand context, the way FileMerge on OS X connects changes and shows their location in the scroll bar (http://firsthand-blog.s3.amazonaws.com/2011/10/yellow-bird-project-spree-upgrade-filemerge-schema.png), etc. No backend work needs to be done to make that happen; the work is isolated in one component and toolset.

> I thought analysts were only using Versionista for viewing diffs

They are, but the whole point of this work is to get to where they *never look at Versionista again.*

**Comment by Mr0grog** [comment]
Also, on the point of structured representations, that representation could totally be HTML, but it needs to be done in a way that doesn't interfere with the content of the versions being diffed (e.g. My use of a `data-wm-change` attribute (unlikely to interfere with attributes from the original content) in my first example to carry extra contextual, machine-readable information about the change.

**Comment by Mr0grog** [comment]
Similarly, you'd need to be *very* careful about `<ins>` and `<del>` tags in this context, too, because just the tag is not enough to clearly indicate that it is an instruction from our differ—the underlying content could have its own `<ins>` and `<del>` tags. You'd need an unambiguous class or attribute on it.

**Comment by janakrajchadha** [comment]
>Similarly, you'd need to be very careful about <ins> and <del> tags in this context,

FYI, the `lxml` functions are designed in a way to remove any existing `<ins>` and `<del>` tags. While I agree with you on the issue of not interfering with the original content of the versions, I don't think we'll come across too many `ins` or `del` classes because of our specific interest in some domains. I could be wrong here but I think we'll really have to check if and where are these tags used frequently.

**Comment by Mr0grog** [comment]
> I don't think we'll come across too many ins or del classes because of our specific interest in some domains.

I disagree:

- I just ran a quick job looking at the content of 9136 of our stored versions. There were 466 pages (5.1%) that use `<ins>` or `<del>`. They are there and in use, even if it’s not super common.

- If we want to render the page and highlight the differences (which is one of the goals here), we should be presenting the rendered page as faithfully as possible. If the page has `<ins>` or `<del>` tags and has CSS styles associated with them, we should try to make sure those styles are faithfully rendered.

- Lots of other orgs (both in the US and internationally) have expressed interest in using this tool to monitor other government web sites. IA has also expressed interest in using our diffing infrastructure if it works out well. The wider this goes, the more likely we are to see HTML with `<ins>` and `<del>` tags.

**Comment by Mr0grog** [comment]
For future reference: all our raw Versionista data is stored in AWS’s Oregon (`us-west-2`) region, so if you want to run a job and look at a sample of the content, spin up a machine in that region to do it (so you have no data transfer costs and high speeds).

**Comment by janakrajchadha** [comment]
>There were 466 pages (5.1%) 

That's a good share of pages and we should definitely not ignore them. 

>we should try to make sure those styles are faithfully rendered

I agree that we should make sure that all pages are faithfully rendered. 

I'm just wondering why `lxml` developers haven't considered this.
Anyway, I think I have an idea of how to build this from the cleanup level itself.

Thanks for running the job and summarizing the results.

> so if you want to run a job and look at a sample of the content, spin up a machine in that region to do it

I have never done this before. Could you direct me to a quick guide on this?
I can probably figure this out by going through the AWS documentation but I really don't want to miss any step in the entire process which you've been following till now.

**Comment by Mr0grog** [comment]
These two guides look like pretty decent walkthroughs for setting up a VM on EC2:
- https://momatajbegum.wordpress.com/2017/03/20/lab4-introduction-to-amazon-elastic-compute-cloud-ec2-with-linux-server/
- https://naveenvasamsetty.wordpress.com/2016/01/14/introduction-to-amazon-elastic-compute-cloud-ec2/

But there is a lot of stuff out there if you Google for it.
