### ISSUE TITLE
Experiment with prioritization

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#7]
A lot of people are excited to work on automated filtering/prioritization. It will be easier to work in parallel and compare results if we have a common interface. How about this:

* You are given an unordered collection of Diffs. Each one has a uuid.
* You are expected to return a mapping of each uuid to a float between 0 and 1, where 1 is interesting and 0 is junk.

Any other suggestions?

**Comment by Mr0grog** [comment]
@danielballan should we consider this to have been done with edgi-govdata-archiving/web-monitoring-db#406 (obviously there are lots of improvements to make, but it is a working and well-used feature now).

**Comment by Mr0grog** [comment]
Circling back around; I’m marking this as complete.
