### ISSUE TITLE
Text diff includes some HTML code

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#70]
I think this a conditional comment intended to enable/disable code in certain versions of Internet Explorer, but the text diff here starts with `<![endif]`

https://api-staging.monitoring.envirodatagov.org/api/v0/pages/c43413cb-2939-4d34-bb0f-e8ddac22e9e2/changes/e7d1062b-e5d5-42b8-8a2d-e3b7c015f7f4..8693b164-3814-494c-b3c2-a86164b42ffe/diff/html_text

That same diff also has some `<p>`, `<h1>`, and `<br />` markup (snapshot from web-monitoring-ui):

<img width="653" alt="screen shot 2017-07-26 at 6 06 25 pm" src="https://user-images.githubusercontent.com/74178/28649929-30b41d7a-722d-11e7-87b2-f365c9f0fe41.png">

**Comment by janakrajchadha** [comment]
Looks like the module we're using to extract text from the HTML is unable to catch these tags. I'll check if similar issues have been reported and look for a fix.

**Comment by janakrajchadha** [comment]
@Mr0grog Since we are only looking for the text, will it make sense to completely ignore conditional comments irrespective of their purpose on the particular page?

**Comment by Mr0grog** [comment]
Well, we absolutely should not have the contents of comments in the text diff. That's definitely wrong.

As for conditional comments, I think it's probably safe to skip them. Ideally, we’d include any visible text that was in them, but practically speaking, they're generally used to add special CSS or JS to a page and not for user-visible text.

**Comment by janakrajchadha** [comment]
We could check for text inside the conditional comments but I don't think the text will actually prove to be useful in most cases.

**Comment by mhucka** [comment]
Just to chime in on this: conditional comments are browser-specific, and I believe are only understood by older versions of Microsoft's Internet Explorer. (According to this [wikipedia page](https://en.wikipedia.org/wiki/Conditional_comment), they stopped being supported in IE10 onward.) These days, IE is not even the most popular browser, which means most users do not see anything that might be triggered by conditional comments. In other words, what most users see is what would be rendered if the comments were removed entirely.

So, I don't think we need to check the text inside conditional comments.

Browser statistics:
• [Wikipedia page](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers)
• [w3counter.com](https://www.w3counter.com/globalstats.php)
• [w3schools](https://www.w3schools.com/Browsers/default.asp)
