### ISSUE TITLE
Implement test of pagefreezer diff

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#75]
I added a stub for testing the `pagefreezer` diff in #68, but it still needs to be implemented. It looks like We’ll need to mock/stub `requests` in order to do so. (Or maybe just mock `web_monitoring.pagefreezer.compare` or `web_monitoring.pagefreezer.PageFreezer.run_query`?)

**Comment by Mr0grog** [comment]
Specifically, the fix we should regression test is in: 5e6f10c1188651ad7eebab7797dde4b669343c9d

**Comment by lightandluck** [comment]
Now that we aren't using pagefreezer anymore, can we close this?

**Comment by Mr0grog** [comment]
This is different and totally unrelated to PageFreezer archives. As long as [we still have PageFreezer diffs implemented](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/diffing_server.py#L25), we should have a test, so this is a valid issue. (That said, I would not be opposed to simply removing the PageFreezer diff — @danielballan?)
