### ISSUE TITLE
Add diff for changes only (html and text) 

### ISSUE THREAD

**Issue by janakrajchadha** [edgi-govdata-archiving/web-monitoring-processing#79]
Based on the discussion during the dev call on Wednesday. 
Sometimes, analysts and developers prefer to view the changes only instead of searching the entire page for them. It'll be helpful if there's an option for this in our diffing server.
This option is already available in Versionista.

**Comment by Mr0grog** [comment]
I don't think we need to do anything on the processing side for this—the existing diffs already provide everything the the UI needs to do this. This is purely a UI issue.

**Comment by janakrajchadha** [comment]
We can do this on either end. It's a simple fix on the processing side as well. Do you want me to close this and open another issue in the `ui` repo?

**Comment by Mr0grog** [comment]
There is already an issue and @lightandluck is already working on it: edgi-govdata-archiving/web-monitoring-ui#102

**Comment by Mr0grog** [comment]
There are very good reasons *not* to do this on the backend: most importantly, that we eventually want to get to a place where we can have some more interesting interactions and progressively disclose more context. This is also what I was getting at over on https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/69#issuecomment-321423260

**Comment by janakrajchadha** [comment]
> most importantly, that we eventually want to get to a place where we can have some more interesting interactions

I've been thinking about this and I think I can really see why you'd want to add interesting ways to display things on a single diff from the backend. 
I think it makes sense to close this and redirect people to the ui issue.

**Comment by janakrajchadha** [comment]
This issue is now being handled in the ui.
The issue can be found here - [edgi-govdata-archiving/web-monitoring-ui#102](https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/102)

**Comment by janakrajchadha** [comment]
@Mr0grog After putting some thought into this, I have realized that functions which return changes only will be helpful for future work in processing.
Have fixed this in #85 
Reopening this.

**Comment by danielballan** [comment]
I agree with the general sentiment that we will want to filter out context and focus on changes, but I don't think there's anything specifically actionable about this issue, so in the spirit of cleaning house I'm going to close this.

**Comment by lightandluck** [comment]
We said we were going to close this, but didn't. Closing
