### ISSUE TITLE
Analysis of insignificant changes dictionary

### ISSUE THREAD

**Issue by janakrajchadha** [edgi-govdata-archiving/web-monitoring-processing#80]
The analyst team maintain a dictionary of insignificant changes which they have created after analysing thousands of changes across various webpages. 
To create filters which can identify insignificant changes and their category, the dictionary had to be thoroughly analysed. This included looking at the diffs in multiple modes (original page, source only, text only) with the help of Versionista's diffing interface.

After spending a considerable amount of time looking at these diffs, I was able to notice some patterns in the frequently occurring changes and started working on filters.

These included the following category of changes -
1. Date/ Time changes
2. Embedded social media feeds
3. Contact info changes

These were the categories which followed patterns that can be identified by just looking at the structure. The filter only assigns these changes a low priority and does __not__ delete them from the data.

More patterns can be added after a more thorough study of the dictionary as more changes are added to it regularly. 

The current filtering work can be found here - https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/filtering.py

**Comment by janakrajchadha** [comment]
@suchthis As per your suggestions in the eval, I've added an issue for the background research work done.

**Comment by janakrajchadha** [comment]
@suchthis This task was completed earlier, I suppose it makes sense to close the issue.
Please let me know if I should once you've taken a look. :)

**Comment by suchthis** [comment]
Looks good. Thanks for doing @janakrajchadha!
