### ISSUE TITLE
Design ETL pipeline

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-processing#9]
_From @ambergman on February 11, 2017 22:44_

What do we need from the incoming data?

_Copied from original issue: edgi-govdata-archiving/filtration#1_

**Comment by dcwalk** [comment]
_From @DSLituiev on February 11, 2017 22:52_

We need to build a pipeline that takes difference set from page freezer so that further we can produce categorization of text chunks.

**Comment by dcwalk** [comment]
_From @aschn on February 11, 2017 23:59_

step 0: incoming data format (issue TODO)
step 1: naive deduplication (issue #6)
step 2: create separate pipeline from image changes (issue TODO)
step 3: feature extraction (issue #4)
step 4: clustering (issue TODO)
step 5: score cluster quality (issue #8)
step 6: rank clusters on importance (issue #7)
step 7: output (issue TODO)

**Comment by janakrajchadha** [comment]
@dcwalk I think the wrong issues have been tagged with the steps here.
For example : - Naive deduplicaton is issue #14 and feature extraction is issue #12.

**Comment by dcwalk** [comment]
@janakrajchadha you are right, thanks for the catch. We merged our issues over to this repo and some of the old auto-lines are in the above. I'm going to remove the issue #'s for now
