### ISSUE TITLE
HTML diff breaks with versions that have differing number of nodes in `<html>`

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#91]
If the number of nodes in the root `<html>` element of a page are different, `html_diff_render` raises an error and breaks.

For example try this one locally: http://localhost:8888/html_visual_diff?format=json&a=https%3A%2F%2Fedgi-versionista-archive.s3.amazonaws.com%2Fversionista1%2F69957-6026604%2Fversion-10666282.html&a_hash=db379f787af3c710e13312fbeb68725a10cd1bd16e6dd221da53bceb2f708cad&b=https%3A%2F%2Fedgi-versionista-archive.s3.amazonaws.com%2Fversionista1%2F69957-6026604%2Fversion-11082551.html&b_hash=6a8160fefe30aa3918f159ce7e0b3082bae491b712f8b2ac0c0fdef3a998e019

That’s from the page https://api.monitoring.envirodatagov.org/api/v0/pages/65d625ec-5f15-433e-8600-ae13937f2b5a, versions:

1. https://api.monitoring.envirodatagov.org/api/v0/versions/5afe9b05-6771-4667-bd2a-8df9e831faeb
2. https://api.monitoring.envirodatagov.org/api/v0/versions/fbb8774d-22a4-48f4-93d6-145f819a0f44

The issue is in [lines 129 and 130 of `differs.py`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/differs.py#L129-L130), where we simply iterate over the nodes of the new content and diff them with the correspondingly indexed nodes of the old content:

```py
diff_list = []
for index in range(len(new_content)):
    diff_list.append(htmldiff(old_content[index], new_content[index]))
```

This isn’t just a problem for differing numbers of nodes, but if whitespace were added, say, between the `<head>` and `<body>` and removed after the `<body>` (so same number of nodes in the end), you’d wind up diffing the `<body>` of one version against whitespace from the other.

The right move here is probably to find the `<head>`, `<body>`, and the source code surrounding them from each version and diff those explicitly.

**Comment by janakrajchadha** [comment]
This is interesting and a little surprising. I did not expect `BeautifulSoup` to count whitespaces as children of a node. I should've checked that myself. 
Are there any other specific cases where you'd expect to have a difference in the number of nodes except for the addition/removal of whitespaces?

**Comment by Mr0grog** [comment]
Lots! You could have anything in those parts of the document (even though you *shouldn’t*). You can also skip the `<head>` element altogether (Google used to do this on their home page to save bytes, for example).

**Comment by janakrajchadha** [comment]
Wow, that's an uncommon yet smart move. 
I've fixed it, so, I'll just push it now.
