### ISSUE TITLE
html_visual_diff transforms quotes, etc. to entities in style/script elements

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#94]
Was trying to figure out what was going on when testing the visual diff and seeing views like this:

![screen shot 2017-09-25 at 2 12 25 pm](https://user-images.githubusercontent.com/74178/30831323-d9335f3a-a1fb-11e7-85ad-a16c8310cc56.png)

Turns out one of the issues (they are myriad) is that the differ is treating the contents of `<script>` and `<style>` elements as HTML, transforming things like quotes into entities (e.g. `&quo;`).

We really need to take the time to look at @anastasia’s [HTML differ](https://github.com/anastasia/htmldiffer) and see if we should switch to it. I have a feeling it likely does not suffer from this issue.

**Comment by Mr0grog** [comment]
(Minor update here: https://github.com/anastasia/htmldiffer does correctly handle the entity issue, but has a couple other bugs that can trigger `combined_diff` to output bad HTML, so there are definitely some things that require being careful there.)

**Comment by danielballan** [comment]
Seems reasonable to deploy them both while we're in the beta phase, to collect more anecdotes about corner cases. I'll get on that...

**Comment by janakrajchadha** [comment]
@Mr0grog What other bugs in @anastasia's code can result in bad HTML?

**Comment by Mr0grog** [comment]
Bugs are filed on its repo.

**Comment by anastasia** [comment]
(heads up: https://github.com/anastasia/htmldiffer/issues?q=is%3Aissue+is%3Aclosed)

**Comment by danielballan** [comment]
Thanks for the update @anastasia. I encoded the issues that Rob found and some others in #108.
