### ISSUE TITLE
AWS Move: redeploy on EC2

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#95]
Amazon has granted us a small bounty of credit, so we are going to work to consolidate ops on AWS (mostly in us-west-2/Oregon for now). We should redeploy the processing diff server on EC2.

- [x] Re-deploy on EC2
- [x] Get API staging/prod servers pointing to new diff server
- [ ] Take Google Cloud deployment down

**Comment by danielballan** [comment]
I have provisionally self-assigned this. Feel free to steal it, as it is not my first prioritize. (The web-monitoring-processing deployment constitutes a small fraction of our Google Cloud usage.)

**Comment by Mr0grog** [comment]
@danielballan everything is redeployed on and pointing to EC2. Do you want to take down the GCloud differ?

**Comment by danielballan** [comment]
Done.
